name: PHP lint CI

on:
  push:
    branches: ['_master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Lint php
        uses: overtrue/phplint@8.1
        with:
          path: .
